### ISSUE TITLE
Version 0.4 fails to install on python3

### ISSUE THREAD

**Issue by satreix** [liluo/pygments-github-lexers#4]
Eveneing liluo, I tried to install pygments-github-lexers with the **0.0.4** version but it appear that the version is not up to date with the version present in the repo.

```
$ pip install pygments-github-lexers

Downloading/unpacking pygments-github-lexers
  ...
  File "~/[...]/pygments_github_lexers/__init__.py", line 3, in <module>
    from github import Dasm16Lexer, PuppetLexer, AugeasLexer, TOMLLexer, SlashLexer

ImportError: No module named 'github'
```

Where the following (kind of) works:

```
$ pip install pygments-github-lexers
$ pip install git+https://github.com/liluo/pygments-github-lexers.git@master
```

I'm saying *kind of* because the setup do not install **pygments** automaticaly.

**Comment by liluo** [comment]
@satreix I'm sorry, fixed it, pls `pip install pygments-github-lexers==0.0.5`
