### ISSUE TITLE
pip install error: ImportError

### ISSUE THREAD

**Issue by thundergolfer** [liluo/pygments-github-lexers#6]
On Windows 10 I am unable to `pip` install this package. 
### Steps
1. enter `pip install pygments-github-lexers` from command line 
### Expected Output

successful install of the package 
### Actual Output

```
line 3, in <module>
       from github import Dasm16Lexer, PuppetLexer, AugeasLexer, TOMLLexer, SlashLexer

ImportError: No module named 'github' 
```

`Command "python setup.py egg_info" failed with error code 1 in C:\....`

**Comment by thundergolfer** [comment]
I have noticed that in the `__init__.py` file the import line appear differently to the error output line. 

`from .github import Dasm16Lexer, PuppetLexer, AugeasLexer, TOMLLexer, SlashLexer`

Perhaps the `.` is necessary to make sure the import is relative, and it isn't in the package code.

**Comment by liluo** [comment]
@thundergolfer 

pls try:

```
pip install -U pygments-github-lexers==0.0.5
```

**Comment by thundergolfer** [comment]
@liluo The above solution works for the single pip install, but I wouldn't solve the problem that [linguist](https://github.com/douban/linguist) has with this dependency would it?
